import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { Shell } from "@/components/mq/Shell";
import { SectionTitle } from "@/components/mq/bits";
import { DISCLAIMER } from "@/lib/mq/data";

export const Route = createFileRoute("/how-it-works")({
  head: () => ({
    meta: [
      { title: "How Prafund works — a month-by-month money simulator" },
      {
        name: "description",
        content:
          "See how Prafund works: pick a career and lifestyle, plan each paycheck, react to unexpected events and track your simulated net worth.",
      },
      { property: "og:title", content: "How Prafund works" },
      {
        property: "og:description",
        content: "Choose, decide, experience, learn, improve, try again — the Prafund loop explained.",
      },
    ],
  }),
  component: HowItWorks,
});

const STEPS = [
  {
    title: "1. Build your life",
    text: "Pick a career from the list. Each one shows a simulated annual salary and an estimated monthly take-home amount so you know what you are working with. Then choose housing, transport and a lifestyle level.",
  },
  {
    title: "2. Make decisions",
    text: "Your paycheck arrives every simulated month. You decide how much goes to savings, how much goes into investments, and whether to pay extra toward debt. Whatever is left stays as cash.",
  },
  {
    title: "3. Face reality",
    text: "Life interrupts. A car repair, a certification offer, a trip with friends, a medical bill. Each option changes your numbers differently, and none of them is automatically the 'right' one.",
  },
  {
    title: "4. See what happens",
    text: "At the end of the month you get a summary: income, spending, savings, investing and the change in net worth. Your financial health score explains exactly what moved it.",
  },
];

function HowItWorks() {
  return (
    <Shell>
      <div className="mx-auto w-full max-w-4xl px-4 py-14">
        <SectionTitle
          eyebrow="How it works"
          title="Choose → Decide → Experience → Learn → Try again"
          sub="Prafund never tells you the one correct answer. It shows you the consequence of the answer you picked."
        />

        <div className="mt-10 space-y-4">
          {STEPS.map((s) => (
            <div key={s.title} className="mq-card p-6">
              <h3 className="text-xl font-bold">{s.title}</h3>
              <p className="mt-2 text-muted-foreground">{s.text}</p>
            </div>
          ))}
        </div>

        <div className="mq-card mt-8 bg-info-soft p-6">
          <h3 className="text-lg font-bold">What the numbers are — and are not</h3>
          <p className="mt-2 text-sm leading-relaxed">
            Salaries, expenses and investment returns in Prafund are simulation assumptions chosen for teaching. Every
            investment result is generated by a model using long-run average return and volatility assumptions plus
            randomness. {DISCLAIMER}
          </p>
        </div>

        <Link
          to="/start"
          className="mt-10 inline-flex items-center gap-2 rounded-xl bg-primary px-6 py-3.5 font-semibold text-primary-foreground"
        >
          Start My Journey <ArrowRight className="size-4" aria-hidden />
        </Link>
      </div>
    </Shell>
  );
}
